//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب معطل.
        /// </summary>
        public static string AccountIsDisabled {
            get {
                return ResourceManager.GetString("AccountIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير موجود في النظام.
        /// </summary>
        public static string AccountIsNotRegistered {
            get {
                return ResourceManager.GetString("AccountIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تاكيد الحساب لـ {0}.
        /// </summary>
        public static string AccountNotConfirmed {
            get {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث بعد التغيير.
        /// </summary>
        public static string ActionOnChange {
            get {
                return ResourceManager.GetString("ActionOnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات على المسار.
        /// </summary>
        public static string ActionsOnPath {
            get {
                return ResourceManager.GetString("ActionsOnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        public static string Activeate {
            get {
                return ResourceManager.GetString("Activeate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكالمات الموظفين.
        /// </summary>
        public static string AgentCalls {
            get {
                return ResourceManager.GetString("AgentCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل المستفيدين.
        /// </summary>
        public static string AllBeneficiaries {
            get {
                return ResourceManager.GetString("AllBeneficiaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي قيمة المتأخرات.
        /// </summary>
        public static string AmountOfLateInstallments {
            get {
                return ResourceManager.GetString("AmountOfLateInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to و.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتأخرات.
        /// </summary>
        public static string Arrears {
            get {
                return ResourceManager.GetString("Arrears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسندة.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسندة بتاريخ.
        /// </summary>
        public static string AssignedAt {
            get {
                return ResourceManager.GetString("AssignedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسند من الموظف.
        /// </summary>
        public static string AssignedFrom {
            get {
                return ResourceManager.GetString("AssignedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسند للموظف.
        /// </summary>
        public static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسناد المكالمة من.
        /// </summary>
        public static string AssignFromUser {
            get {
                return ResourceManager.GetString("AssignFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسناد المكالمة الى.
        /// </summary>
        public static string AssignToUser {
            get {
                return ResourceManager.GetString("AssignToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت اسناد المكالمة الى المستخدم.
        /// </summary>
        public static string AssignToUserAt {
            get {
                return ResourceManager.GetString("AssignToUserAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحملة في المتصل التنبؤي.
        /// </summary>
        public static string AVAYAAURACampaignPredictive {
            get {
                return ResourceManager.GetString("AVAYAAURACampaignPredictive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باستخدام الموقع.
        /// </summary>
        public static string ByApplication {
            get {
                return ResourceManager.GetString("ByApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باستخدام الدومين.
        /// </summary>
        public static string ByDomain {
            get {
                return ResourceManager.GetString("ByDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكالمة.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف الرئيسي.
        /// </summary>
        public static string CallCategoryMain {
            get {
                return ResourceManager.GetString("CallCategoryMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة المكالمة.
        /// </summary>
        public static string CallDuration {
            get {
                return ResourceManager.GetString("CallDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدراة المكالمات.
        /// </summary>
        public static string CallsManagement {
            get {
                return ResourceManager.GetString("CallsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المكالمة.
        /// </summary>
        public static string CallStatus {
            get {
                return ResourceManager.GetString("CallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المكالمة.
        /// </summary>
        public static string CallType {
            get {
                return ResourceManager.GetString("CallType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حملة.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الحملات.
        /// </summary>
        public static string CampaignsManagement {
            get {
                return ResourceManager.GetString("CampaignsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة التصنيفات.
        /// </summary>
        public static string CategoriesManagement {
            get {
                return ResourceManager.GetString("CategoriesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسار التصنيف.
        /// </summary>
        public static string CategoryPath {
            get {
                return ResourceManager.GetString("CategoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مسار التصنيف.
        /// </summary>
        public static string CategoryPathName {
            get {
                return ResourceManager.GetString("CategoryPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من الاسم.
        /// </summary>
        public static string CheckName {
            get {
                return ResourceManager.GetString("CheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من الاسم في النطاق.
        /// </summary>
        public static string CheckNameForDomain {
            get {
                return ResourceManager.GetString("CheckNameForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من اسم الفريق.
        /// </summary>
        public static string CheckNameForTeam {
            get {
                return ResourceManager.GetString("CheckNameForTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الربط.
        /// </summary>
        public static string ConnectorWay {
            get {
                return ResourceManager.GetString("ConnectorWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستفيد.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العقد.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العقد.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العقد.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العقد.
        /// </summary>
        public static string ContractStatus {
            get {
                return ResourceManager.GetString("ContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع القرض.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات مخصصة.
        /// </summary>
        public static string CustomOptions {
            get {
                return ResourceManager.GetString("CustomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعطيل.
        /// </summary>
        public static string DeActiveate {
            get {
                return ResourceManager.GetString("DeActiveate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوفي.
        /// </summary>
        public static string Dead {
            get {
                return ResourceManager.GetString("Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات التفصيلية.
        /// </summary>
        public static string DetailedInformation {
            get {
                return ResourceManager.GetString("DetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد حقول الطلب.
        /// </summary>
        public static string DeterminizeParameters {
            get {
                return ResourceManager.GetString("DeterminizeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد حقول النتيجة.
        /// </summary>
        public static string DeterminizeResults {
            get {
                return ResourceManager.GetString("DeterminizeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكالمات المتصل التنبؤي.
        /// </summary>
        public static string DialerCalls {
            get {
                return ResourceManager.GetString("DialerCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدير المباشر.
        /// </summary>
        public static string DirectLeader {
            get {
                return ResourceManager.GetString("DirectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التعطيل.
        /// </summary>
        public static string DisableCondetion {
            get {
                return ResourceManager.GetString("DisableCondetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معطل.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التعطيل.
        /// </summary>
        public static string DisabledIf {
            get {
                return ResourceManager.GetString("DisabledIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراء جديد.
        /// </summary>
        public static string DoNewAction {
            get {
                return ResourceManager.GetString("DoNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني {0} مسجل مسبقا.
        /// </summary>
        public static string EmailExist {
            get {
                return ResourceManager.GetString("EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوظيفي.
        /// </summary>
        public static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطاع العمل.
        /// </summary>
        public static string EmployerSector {
            get {
                return ResourceManager.GetString("EmployerSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة العمل.
        /// </summary>
        public static string EmployerType {
            get {
                return ResourceManager.GetString("EmployerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهاء المكالمة.
        /// </summary>
        public static string EndCall {
            get {
                return ResourceManager.GetString("EndCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الوصول لنقطة الاتصال.
        /// </summary>
        public static string EndPointError {
            get {
                return ResourceManager.GetString("EndPointError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنجليزية.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط التنفيذ.
        /// </summary>
        public static string ExecuteConditions {
            get {
                return ResourceManager.GetString("ExecuteConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنفيذ الإجراء.
        /// </summary>
        public static string ExecuteTrigger {
            get {
                return ResourceManager.GetString("ExecuteTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ المكالمة المتوقع.
        /// </summary>
        public static string ExpectedCallDate {
            get {
                return ResourceManager.GetString("ExpectedCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير إكسل.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحويلة.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التزامات خارجية.
        /// </summary>
        public static string ExternalObligations {
            get {
                return ResourceManager.GetString("ExternalObligations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت العملية.
        /// </summary>
        public static string FailedOperation {
            get {
                return ResourceManager.GetString("FailedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسئلة الشائعة.
        /// </summary>
        public static string FAQs {
            get {
                return ResourceManager.GetString("FAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات الحقل.
        /// </summary>
        public static string FieldOptions {
            get {
                return ResourceManager.GetString("FieldOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الحقل.
        /// </summary>
        public static string FieldText {
            get {
                return ResourceManager.GetString("FieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول بالعربية.
        /// </summary>
        public static string FirstNameAr {
            get {
                return ResourceManager.GetString("FirstNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول بالإنجليزية.
        /// </summary>
        public static string FirstNameEn {
            get {
                return ResourceManager.GetString("FirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية الوصول.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل بالعربية.
        /// </summary>
        public static string FullNameAr {
            get {
                return ResourceManager.GetString("FullNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل بالإنجليزية.
        /// </summary>
        public static string FullNameEn {
            get {
                return ResourceManager.GetString("FullNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحصول على.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكالمات التاريخية.
        /// </summary>
        public static string HistoricalCalls {
            get {
                return ResourceManager.GetString("HistoricalCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية غير صحيحة.
        /// </summary>
        public static string IncorrectOperation {
            get {
                return ResourceManager.GetString("IncorrectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التأمينات.
        /// </summary>
        public static string InsuranceStatus {
            get {
                return ResourceManager.GetString("InsuranceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات دخول غير صحيحة من {0}.
        /// </summary>
        public static string InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الوفاة.
        /// </summary>
        public static string IsDead {
            get {
                return ResourceManager.GetString("IsDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل الحقل للقراءة فقط ؟.
        /// </summary>
        public static string IsFieldReadOnle {
            get {
                return ResourceManager.GetString("IsFieldReadOnle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل الحقل قابل للتصدير في التقارير.
        /// </summary>
        public static string IsFieldReportExportable {
            get {
                return ResourceManager.GetString("IsFieldReportExportable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل الحقل إجباري عند الظهور في المسار ؟.
        /// </summary>
        public static string IsFieldRequiredOnShow {
            get {
                return ResourceManager.GetString("IsFieldRequiredOnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل هي اخر مكالمة.
        /// </summary>
        public static string IsLatestCall {
            get {
                return ResourceManager.GetString("IsLatestCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر.
        /// </summary>
        public static string ItemsCount {
            get {
                return ResourceManager.GetString("ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف الوظيفي.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string KeepMeLoggedIn {
            get {
                return ResourceManager.GetString("KeepMeLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخير.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ آخر إسناد.
        /// </summary>
        public static string LastAssignedDate {
            get {
                return ResourceManager.GetString("LastAssignedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر مكالمة من الموظف.
        /// </summary>
        public static string LastCallFrom {
            get {
                return ResourceManager.GetString("LastCallFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر حالة.
        /// </summary>
        public static string LastCallStatus {
            get {
                return ResourceManager.GetString("LastCallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير بالعربية.
        /// </summary>
        public static string LastNameAr {
            get {
                return ResourceManager.GetString("LastNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير بالإنجليزية.
        /// </summary>
        public static string LastNameEn {
            get {
                return ResourceManager.GetString("LastNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر مكالمة بتاريخ.
        /// </summary>
        public static string LatestCallAt {
            get {
                return ResourceManager.GetString("LatestCallAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر مكالمة من.
        /// </summary>
        public static string LatestCallBy {
            get {
                return ResourceManager.GetString("LatestCallBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر مكالمة تاريخية.
        /// </summary>
        public static string LatestHistoricalCall {
            get {
                return ResourceManager.GetString("LatestHistoricalCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر الأخبار.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائد الفريق.
        /// </summary>
        public static string LeaderName {
            get {
                return ResourceManager.GetString("LeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة القرض.
        /// </summary>
        public static string LoanAmount {
            get {
                return ResourceManager.GetString("LoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حلول القرض.
        /// </summary>
        public static string LoanTimeStatus {
            get {
                return ResourceManager.GetString("LoanTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات الرئيسية.
        /// </summary>
        public static string MainInfo {
            get {
                return ResourceManager.GetString("MainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الاجتماعية.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل {0} يجب ان لا يتجاوز  {1} أحرف..
        /// </summary>
        public static string MaxLengthMessage {
            get {
                return ResourceManager.GetString("MaxLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل {0} يجب ان لا يقل عن {1} أحرف..
        /// </summary>
        public static string MinLengthMessage {
            get {
                return ResourceManager.GetString("MinLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الواجب سداده لفك الرهن.
        /// </summary>
        public static string MortgageAmount {
            get {
                return ResourceManager.GetString("MortgageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فك الرهن.
        /// </summary>
        public static string MortgageClosed {
            get {
                return ResourceManager.GetString("MortgageClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريدي الإلكتروني.
        /// </summary>
        public static string MyEmail {
            get {
                return ResourceManager.GetString("MyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائياتي.
        /// </summary>
        public static string MyStatistics {
            get {
                return ResourceManager.GetString("MyStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربية.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنجليزية.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافي الراتب.
        /// </summary>
        public static string NetSalary {
            get {
                return ResourceManager.GetString("NetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة إجراء جديد.
        /// </summary>
        public static string NewAction {
            get {
                return ResourceManager.GetString("NewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرط جديد.
        /// </summary>
        public static string NewCondition {
            get {
                return ResourceManager.GetString("NewCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة شروط جديدة.
        /// </summary>
        public static string NewConditionGroup {
            get {
                return ResourceManager.GetString("NewConditionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة إجراء جديد.
        /// </summary>
        public static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة إجراءات جديدة.
        /// </summary>
        public static string NewEventsGroup {
            get {
                return ResourceManager.GetString("NewEventsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيار جديد.
        /// </summary>
        public static string NewOption {
            get {
                return ResourceManager.GetString("NewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد حساب مسجل بـ {0}.
        /// </summary>
        public static string NoAccountsRegistered {
            get {
                return ResourceManager.GetString("NoAccountsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون عقد.
        /// </summary>
        public static string NoContract {
            get {
                return ResourceManager.GetString("NoContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات للعرض.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تحديد أي خيار.
        /// </summary>
        public static string NoOptionCanSet {
            get {
                return ResourceManager.GetString("NoOptionCanSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متوفي.
        /// </summary>
        public static string NotDead {
            get {
                return ResourceManager.GetString("NotDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موجود.
        /// </summary>
        public static string NotExisted {
            get {
                return ResourceManager.GetString("NotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} غير موجود.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيه.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير منتظم.
        /// </summary>
        public static string NotRegular {
            get {
                return ResourceManager.GetString("NotRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notsuccess.
        /// </summary>
        public static string Notsuccess {
            get {
                return ResourceManager.GetString("Notsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الرد ( تنبؤي ).
        /// </summary>
        public static string NotSuccessByDialer {
            get {
                return ResourceManager.GetString("NotSuccessByDialer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر في الصفحة.
        /// </summary>
        public static string NumberOfItemsPerPage {
            get {
                return ResourceManager.GetString("NumberOfItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأقساط المتأخرة.
        /// </summary>
        public static string NumberOfLateInstallments {
            get {
                return ResourceManager.GetString("NumberOfLateInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التفعيل.
        /// </summary>
        public static string OnActivate {
            get {
                return ResourceManager.GetString("OnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند الضغط.
        /// </summary>
        public static string OnClick {
            get {
                return ResourceManager.GetString("OnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند الإرسال.
        /// </summary>
        public static string OnSubmit {
            get {
                return ResourceManager.GetString("OnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند التحديث.
        /// </summary>
        public static string OnUpdate {
            get {
                return ResourceManager.GetString("OnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند العرض.
        /// </summary>
        public static string OnView {
            get {
                return ResourceManager.GetString("OnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخيارات.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خيارات من كيانات النظام.
        /// </summary>
        public static string OptionsFromSystemEntities {
            get {
                return ResourceManager.GetString("OptionsFromSystemEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أو.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقساط المدفوعة.
        /// </summary>
        public static string PaidInstallments {
            get {
                return ResourceManager.GetString("PaidInstallments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحقل.
        /// </summary>
        public static string ParameterName {
            get {
                return ResourceManager.GetString("ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المدفوع.
        /// </summary>
        public static string PartAmount {
            get {
                return ResourceManager.GetString("PartAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string PartDiscount {
            get {
                return ResourceManager.GetString("PartDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللإعفاء.
        /// </summary>
        public static string PartExcuse {
            get {
                return ResourceManager.GetString("PartExcuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجزء.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 محارف على الأقل.
        /// </summary>
        public static string PasswordAlertCharactersLenth {
            get {
                return ResourceManager.GetString("PasswordAlertCharactersLenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرف صغير على الأقل.
        /// </summary>
        public static string PasswordAlertLowercaseLetter {
            get {
                return ResourceManager.GetString("PasswordAlertLowercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم واحد على الأقل.
        /// </summary>
        public static string PasswordAlertNumber {
            get {
                return ResourceManager.GetString("PasswordAlertNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطابق كلمتا المرور.
        /// </summary>
        public static string PasswordAlertPasswordsMatch {
            get {
                return ResourceManager.GetString("PasswordAlertPasswordsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز على الأقل.
        /// </summary>
        public static string PasswordAlertSymbol {
            get {
                return ResourceManager.GetString("PasswordAlertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حرف كبير على الأقل.
        /// </summary>
        public static string PasswordAlertUppercaseLetter {
            get {
                return ResourceManager.GetString("PasswordAlertUppercaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل {0} لايمكن ان يقل عن  {1} احرف..
        /// </summary>
        public static string PasswordLengthMessage {
            get {
                return ResourceManager.GetString("PasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور وتأكيد كلمة المرور يجب أن تتطابقان.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء إعادة تعيين كلمة المرور..
        /// </summary>
        public static string PasswordResetErrorMessage {
            get {
                return ResourceManager.GetString("PasswordResetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور بنجاح..
        /// </summary>
        public static string PasswordResetSuccesMessage {
            get {
                return ResourceManager.GetString("PasswordResetSuccesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمات المرور غير متطابقة.
        /// </summary>
        public static string PasswordsNotMatched {
            get {
                return ResourceManager.GetString("PasswordsNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجراءات المسار.
        /// </summary>
        public static string PathActions {
            get {
                return ResourceManager.GetString("PathActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقل في المسار.
        /// </summary>
        public static string PathField {
            get {
                return ResourceManager.GetString("PathField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المسار.
        /// </summary>
        public static string PathInfo {
            get {
                return ResourceManager.GetString("PathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة السؤال.
        /// </summary>
        public static string PathResult {
            get {
                return ResourceManager.GetString("PathResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة السؤال.
        /// </summary>
        public static string PathValue {
            get {
                return ResourceManager.GetString("PathValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السدادات.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصدر السداد.
        /// </summary>
        public static string PaySource {
            get {
                return ResourceManager.GetString("PaySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة المئوية للمعايير المختارة .
        /// </summary>
        public static string PercentageOfSelectedCriteria {
            get {
                return ResourceManager.GetString("PercentageOfSelectedCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال 2.
        /// </summary>
        public static string PhoneNumber2 {
            get {
                return ResourceManager.GetString("PhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضلاً اختر نوع الخيارات.
        /// </summary>
        public static string PleaseSelectOptionType {
            get {
                return ResourceManager.GetString("PleaseSelectOptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أولوية.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في النظام (التنبؤي).
        /// </summary>
        public static string QueuedInDialer {
            get {
                return ResourceManager.GetString("QueuedInDialer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في النظام.
        /// </summary>
        public static string QueuedInSystem {
            get {
                return ResourceManager.GetString("QueuedInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recall.
        /// </summary>
        public static string Recall {
            get {
                return ResourceManager.GetString("Recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإيصال.
        /// </summary>
        public static string ReceiptDateH {
            get {
                return ResourceManager.GetString("ReceiptDateH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظم.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتظم جزئياً.
        /// </summary>
        public static string RegularPartly {
            get {
                return ResourceManager.GetString("RegularPartly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتبقي.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة القسط.
        /// </summary>
        public static string RepayAmount {
            get {
                return ResourceManager.GetString("RepayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ حلول القسط.
        /// </summary>
        public static string RepayDateH {
            get {
                return ResourceManager.GetString("RepayDateH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القسط.
        /// </summary>
        public static string RepayNumber {
            get {
                return ResourceManager.GetString("RepayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقل {0} مطلوب ..
        /// </summary>
        public static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعين كلمة السر.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم حقل النتيجة.
        /// </summary>
        public static string ResultName {
            get {
                return ResourceManager.GetString("ResultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التقاعد.
        /// </summary>
        public static string RetirementStatus {
            get {
                return ResourceManager.GetString("RetirementStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل الرضا.
        /// </summary>
        public static string Satisfaction {
            get {
                return ResourceManager.GetString("Satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدولة المكالمة بواسطة.
        /// </summary>
        public static string ScheduledByUser {
            get {
                return ResourceManager.GetString("ScheduledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ جدولة المكالمة.
        /// </summary>
        public static string ScheduledCallDate {
            get {
                return ResourceManager.GetString("ScheduledCallDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة (التنبؤي).
        /// </summary>
        public static string ScheduledInDialer {
            get {
                return ResourceManager.GetString("ScheduledInDialer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة.
        /// </summary>
        public static string ScheduledInSystem {
            get {
                return ResourceManager.GetString("ScheduledInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدولت لعنوان IP .
        /// </summary>
        public static string ScheduledToIPAddress {
            get {
                return ResourceManager.GetString("ScheduledToIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدولة المكالمة الى.
        /// </summary>
        public static string ScheduledToUser {
            get {
                return ResourceManager.GetString("ScheduledToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدولت للمستخدم في.
        /// </summary>
        public static string ScheduledToUserAt {
            get {
                return ResourceManager.GetString("ScheduledToUserAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني بالعربية.
        /// </summary>
        public static string SecondNameAr {
            get {
                return ResourceManager.GetString("SecondNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني بالإنجليزية.
        /// </summary>
        public static string SecondNameEn {
            get {
                return ResourceManager.GetString("SecondNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع الإجراء.
        /// </summary>
        public static string SelectActionType {
            get {
                return ResourceManager.GetString("SelectActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر حالة المكالمة.
        /// </summary>
        public static string SelectCallStatus {
            get {
                return ResourceManager.GetString("SelectCallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الحملة.
        /// </summary>
        public static string SelectCampaign {
            get {
                return ResourceManager.GetString("SelectCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر تصنيف.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر شرط.
        /// </summary>
        public static string SelectCondition {
            get {
                return ResourceManager.GetString("SelectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر التاريخ.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الاختيار التلقائي.
        /// </summary>
        public static string SelectedIf {
            get {
                return ResourceManager.GetString("SelectedIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الموظف.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الحقل.
        /// </summary>
        public static string SelectField {
            get {
                return ResourceManager.GetString("SelectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الفريق.
        /// </summary>
        public static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ من المخدم.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عدم إدخال معرف.
        /// </summary>
        public static string ShouldNotInsertIdentifier {
            get {
                return ResourceManager.GetString("ShouldNotInsertIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الإظهار.
        /// </summary>
        public static string ShowCondetion {
            get {
                return ResourceManager.GetString("ShowCondetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض كلمة المرور.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض النتائج.
        /// </summary>
        public static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم بريدك الإلكتروني للدخول.
        /// </summary>
        public static string SigninWithYourDomainAccount {
            get {
                return ResourceManager.GetString("SigninWithYourDomainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم حسابك في النظام للدخول.
        /// </summary>
        public static string SigninWithYourSystemAccount {
            get {
                return ResourceManager.GetString("SigninWithYourSystemAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الماءة المالية.
        /// </summary>
        public static string Solvency {
            get {
                return ResourceManager.GetString("Solvency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحصائيات.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متعثر.
        /// </summary>
        public static string Stumbled {
            get {
                return ResourceManager.GetString("Stumbled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التعثر.
        /// </summary>
        public static string StumbleType {
            get {
                return ResourceManager.GetString("StumbleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنجاح.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح ....
        /// </summary>
        public static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة الفرق.
        /// </summary>
        public static string TeamsManagement {
            get {
                return ResourceManager.GetString("TeamsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحملات.
        /// </summary>
        public static string TheCampaigns {
            get {
                return ResourceManager.GetString("TheCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد المعروض حالياً.
        /// </summary>
        public static string TheCurrentNumber {
            get {
                return ResourceManager.GetString("TheCurrentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        public static string TheJob {
            get {
                return ResourceManager.GetString("TheJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        public static string TheList {
            get {
                return ResourceManager.GetString("TheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string TheMain {
            get {
                return ResourceManager.GetString("TheMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات.
        /// </summary>
        public static string TheOperations {
            get {
                return ResourceManager.GetString("TheOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسارات.
        /// </summary>
        public static string ThePathes {
            get {
                return ResourceManager.GetString("ThePathes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأذونات.
        /// </summary>
        public static string ThePermissions {
            get {
                return ResourceManager.GetString("ThePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string TheReports {
            get {
                return ResourceManager.GetString("TheReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string TheRoles {
            get {
                return ResourceManager.GetString("TheRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإحصائيات.
        /// </summary>
        public static string TheStatistics {
            get {
                return ResourceManager.GetString("TheStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرق.
        /// </summary>
        public static string TheTeams {
            get {
                return ResourceManager.GetString("TheTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث بالعربية.
        /// </summary>
        public static string ThirdNameAr {
            get {
                return ResourceManager.GetString("ThirdNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثالث بالإنجليزية.
        /// </summary>
        public static string ThirdNameEn {
            get {
                return ResourceManager.GetString("ThirdNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت فترة صلاحية الجلسة في النظام.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المصروف.
        /// </summary>
        public static string TotalExpense {
            get {
                return ResourceManager.GetString("TotalExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي المسدد.
        /// </summary>
        public static string TotalPaid {
            get {
                return ResourceManager.GetString("TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد التدريبية.
        /// </summary>
        public static string TrainingMaterials {
            get {
                return ResourceManager.GetString("TrainingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية وصول.
        /// </summary>
        public static string UnauthorizeMessage {
            get {
                return ResourceManager.GetString("UnauthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب ليس لديه صلاحيات على النظام.
        /// </summary>
        public static string UserHasNoRole {
            get {
                return ResourceManager.GetString("UserHasNoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم {0} مسجل مسبقا.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود مسبقاً.
        /// </summary>
        public static string UsernameIsExistedBefore {
            get {
                return ResourceManager.GetString("UsernameIsExistedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور غير صحيح.
        /// </summary>
        public static string UsernameOrPasswordIsNotValid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  معرف الوقت الحقيقي للمستخدم.
        /// </summary>
        public static string UserRealTimeId {
            get {
                return ResourceManager.GetString("UserRealTimeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string UsersManagement {
            get {
                return ResourceManager.GetString("UsersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز  إعادة تعيين كلمة المرور هو - {0}.
        /// </summary>
        public static string YourToken {
            get {
                return ResourceManager.GetString("YourToken", resourceCulture);
            }
        }
    }
}
